_target_: src.models.img2pbr_module.IMG2PBRLitModule

model:
  _target_: src.models.components.unet_multi_decoder.UNetMultiDecoderModel
  in_channels: 3
  out_channels:
    - 3  # albedo
    - 3  # normal
    - 1  # roughness
    - 1  # metalness
  num_conv_blocks: 1
  channel_mult: [1, 1, 1, 1]
  use_self_attention: False
  use_ViT_bottleneck: False
  use_MLP_out: False
  use_fp16: False

loss:
  _target_: src.models.components.losses.pbr_recloss.PBRReconstructionLoss
  random_per_loss_weight: 0.
  per_loss_weight: 0.
  render_loss_weight: 0.  # not implementation
  gan_loss_weight: 0.  # not implementation

optimizer:
  _target_: torch.optim.Adam
  _partial_: True
  lr: 1.e-3
  weight_decay: 0.

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: True
  mode: min
  min_lr: 1.e-6
  factor: 0.1
  patience: 10
  

