# @package _global_

defaults:
  - _self_
  - data: mnist # choose datamodule with `test_dataloader()` for evaluation
  - model: mnist
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default
  - experiment: null

override /task_name: "pbr_reconstruction/eval"

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
